# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38b1a590597f6e3f003bef71086f88045c0f024a058b1acea619802bdc1639bbee6ddea90b27edcd0a11d64bc9e65597ccef314c43963137c06129abb7784435

test:
  secret_key_base: 951f8166a49810d65d284dd2feb18a996a4b6e63af03266cb3c6b9269b0d85a432d13fc0afaa6d6326e9ef71f38080a5c19855244fefcc6b607ab46b49c60381

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
